<a href="https://colab.research.google.com/github/RyanBrumbaugh/Projects/blob/main/Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Data**

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()
fileName = "agaricus-lepiota.data"
data = pd.read_csv("agaricus-lepiota.data")

Saving agaricus-lepiota.data to agaricus-lepiota (1).data


In [ ]:
import numpy as np #normal packages importing
import pandas as pd

data = pd.read_csv('agaricus-lepiota.data', header=None) #read in data and save it as data dataframe
data

0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0     p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1     e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2     e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3     p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4     e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
8119  e  k  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  b  c  l
8120  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  n  o  p  b  v  l
8121  e  f  s  n  f  n  a  c  b  n  ...  s  o  o  p  o  o  p  b  c  l
8122  p  k  y  n  f  y  f  c  n  b  ...  k  w  w  p  w  o  e  w  v  l
8123  e  x  s  n  f  n  a  c  b  y  ...  s  o  o  p  o  o  p  o  c  l

[8124 rows x 23 columns]

# **Renaming the columns based on the Agaricus-lepiota.names so it is easier to read**

In [ ]:
column_names = ['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises?', 'odor', 'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color', 'stalk-shape', 'stalk-root', 'stalk-surface-above-ring', 'stalk-surface-below-ring', 'stalk-color-above-ring',  'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number', 'ring-type', 'spore-print-color', 'population', 'habitat']

In [ ]:
column_names #checking to make sure the names are all correct

['class',
 'cap-shape',
 'cap-surface',
 'cap-color',
 'bruises?',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'gill-color',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-type',
 'veil-color',
 'ring-number',
 'ring-type',
 'spore-print-color',
 'population',
 'habitat']

In [ ]:
data.columns = column_names #assigning these columns to the data frame

In [ ]:
data.info() #double check that it worked

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises?                  8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [ ]:
data

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0        p         x           s         n        t    p               f   
1        e         x           s         y        t    a               f   
2        e         b           s         w        t    l               f   
3        p         x           y         w        t    p               f   
4        e         x           s         g        f    n               f   
...    ...       ...         ...       ...      ...  ...             ...   
8119     e         k           s         n        f    n               a   
8120     e         x           s         n        f    n               a   
8121     e         f           s         n        f    n               a   
8122     p         k           y         n        f    y               f   
8123     e         x           s         n        f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

##Finding the missing indices

In [ ]:
missing_indices = (data['stalk-root'] == '?')

In [ ]:
missing_indices = np.asarray(missing_indices)

In [ ]:
missing_indices

array([False, False, False, ...,  True,  True,  True])

#**Get Feature Data**
Drop response values from the dataframe

In [ ]:
feature_data = (data.drop(columns=['stalk-root'])) #getting the features column by dropping response

In [ ]:
from sklearn.preprocessing import OneHotEncoder
OHE = OneHotEncoder(sparse=False) #train OneHotEncoder
features_encoded = OHE.fit_transform(feature_data) #fit and tranform the dataset with OHE

In [ ]:
features_encoded

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
features_test = features_encoded[missing_indices == True]

In [ ]:
features_train = features_encoded[missing_indices == False]

#**Get Response Data**

In [ ]:
response_data = (data[['stalk-root']]) #get the column with stock-root

In [ ]:
from sklearn import preprocessing
  
le = preprocessing.LabelEncoder()

response_encoded = le.fit_transform(response_data)#Label encode responses 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
response_test = response_encoded[missing_indices == True] #getting responses that are missing

In [ ]:
features_train

array([[0., 1., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [ ]:
response_train = response_encoded[missing_indices == False] #get response data that is not missing

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,
                           p=2,
                           metric='minkowski') #uses euclidian distance

knn.fit(features_train, response_train) #fit the model with the training data without the missing values

predictions = knn.predict(features_test) #make prediction using the data with the missing values

In [ ]:
predictions

array([1, 1, 3, ..., 3, 1, 3])

In [ ]:
missing_values = predictions 

In [ ]:
missing_values =le.inverse_transform(missing_values) #getting the original values for the label encoding back so it matches the data frame

In [ ]:
missing_values

array(['b', 'b', 'e', ..., 'e', 'b', 'e'], dtype=object)

In [ ]:
print(missing_values[:10]) #print the first 10 intances

['b' 'b' 'e' 'b' 'b' 'b' 'b' 'b' 'b' 'e']


In [ ]:
copy_of_data = data.copy()

In [ ]:
copy_of_data

In [ ]:
copy_of_data.loc[missing_indices, "stalk-root"] = missing_values

In [ ]:
copy_of_data

class cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0        p         x           s         n        t    p               f   
1        e         x           s         y        t    a               f   
2        e         b           s         w        t    l               f   
3        p         x           y         w        t    p               f   
4        e         x           s         g        f    n               f   
...    ...       ...         ...       ...      ...  ...             ...   
8119     e         k           s         n        f    n               a   
8120     e         x           s         n        f    n               a   
8121     e         f           s         n        f    n               a   
8122     p         k           y         n        f    y               f   
8123     e         x           s         n        f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

##**Training RandomForest and Logistic Classifier**

In [ ]:
X= copy_of_data.loc[:, copy_of_data.columns != 'class']  # Get the Features from data with no missing values
y= copy_of_data.loc[:, copy_of_data.columns == 'class']  # Get the Responses from data with no missing values

In [ ]:
OHE_for_classifier = OHE.fit_transform(X) #transform the data so we can train/test split

In [ ]:
le_for_classifier = le.fit_transform(y)#Label encode responses 

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.model_selection import train_test_split

X= OHE_for_classifier  # Features
y= le_for_classifier  # response

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.20) #split so we can train teh RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=42) #Create a Random Forest Classifier
%time rf.fit(X_train,y_train) #timing how long it takes to fit the model
y_pred = rf.predict(X_test)

CPU times: user 467 ms, sys: 11.3 ms, total: 479 ms
Wall time: 491 ms


In [ ]:
from sklearn.linear_model import LogisticRegression #Train LogisticRegression Model

lr = LogisticRegression(random_state=42)
%time lr.fit(X_train,y_train) #timing how long it takes to fit the model
z_pred = lr.predict(X_test)

CPU times: user 218 ms, sys: 92.6 ms, total: 310 ms
Wall time: 184 ms


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
print("RandomForestClassifier:",
      "Accuracy Score:", accuracy_score(y_test, y_pred),
      "Recall Score:",recall_score(y_test, y_pred),
      "Precision Score:",precision_score(y_test, y_pred))

RandomForestClassifier: Accuracy Score: 1.0 Recall Score: 1.0 Precision Score: 1.0


In [ ]:
print("LogisticRegression:",
      "Accuracy Score:", accuracy_score(y_test, z_pred),
      "Recall Score:",recall_score(y_test, z_pred),
      "Precision Score:",precision_score(y_test, z_pred))

LogisticRegression: Accuracy Score: 1.0 Recall Score: 1.0 Precision Score: 1.0


#**Use PCA To Reduce Dimensionality**

In [ ]:
Z= copy_of_data.loc[:, copy_of_data.columns != 'class']  # Get the Features from data with no missing values
A= copy_of_data.loc[:, copy_of_data.columns == 'class']  # Get the Responses from data with no missing values

In [ ]:
OHE_for_classifier = OHE.fit_transform(Z) #transform the data so we can train/test split

In [ ]:
le_for_classifier = le.fit_transform(A)#Label encode responses data

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.model_selection import train_test_split

Z= OHE_for_classifier  # Features
A= le_for_classifier  # response

Z_train, Z_test, A_train, A_test = train_test_split(Z, A, test_size=0.2, random_state=0)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = .95) #% of data that we want to keep

In [ ]:
Z_train = pca.fit_transform(Z_train)#we reduced the number of dimensions from 116 to 41
Z_test = pca.transform(Z_test)#we reduced the number of dimensions from 116 to 41

In [ ]:
pca.explained_variance_ratio_.cumsum() #gives the number of dimensions in order to maintain 95% variance by adding each dimensions amount of variacne saved

array([0.16694159, 0.29346506, 0.39867942, 0.46181295, 0.50017345,
       0.5364768 , 0.56760011, 0.59781388, 0.62450687, 0.64565587,
       0.66623014, 0.68559917, 0.70374108, 0.72104506, 0.73682914,
       0.75231068, 0.76693274, 0.7812095 , 0.79454373, 0.80654244,
       0.81737794, 0.82806913, 0.83813792, 0.84768348, 0.85683264,
       0.86554168, 0.87365208, 0.88155743, 0.88893661, 0.8959733 ,
       0.90280762, 0.90917834, 0.91544657, 0.921106  , 0.92650641,
       0.93168794, 0.93655226, 0.94123451, 0.94560102, 0.9498879 ,
       0.95402596])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(random_state=42) #Create a Random Forest Classifier
%time rf.fit(Z_train,A_train) #timing how long it takes to fit the model
B_pred = rf.predict(Z_test)

CPU times: user 2.64 s, sys: 51.9 ms, total: 2.69 s
Wall time: 2.66 s


In [ ]:
from sklearn.linear_model import LogisticRegression #Train LogisticRegression Model

lr = LogisticRegression(random_state=42)
%time lr.fit(Z_train,A_train) #timing how long it takes to fit the model
C_pred = lr.predict(Z_test)

CPU times: user 110 ms, sys: 57.1 ms, total: 167 ms
Wall time: 97.6 ms


In [ ]:
print("LogisticRegression:",
      "Accuracy Score:", accuracy_score(A_test, C_pred),
      "Recall Score:",recall_score(A_test, C_pred),
      "Precision Score:",precision_score(A_test, C_pred))

LogisticRegression: Accuracy Score: 0.9944615384615385 Recall Score: 0.9935316946959897 Precision Score: 0.9948186528497409


In [ ]:
print("RandomForestClassifier:",
      "Accuracy Score:", accuracy_score(A_test, B_pred),
      "Recall Score:",recall_score(A_test, B_pred),
      "Precision Score:",precision_score(A_test, B_pred))

RandomForestClassifier: Accuracy Score: 1.0 Recall Score: 1.0 Precision Score: 1.0
